/**
 * Соответствие русских названий болезней (с экрана диагностики) и имён файлов в dist/images/diseases.
 * Имена файлов — без расширения, в точности как в папке (регистр и пробелы).
 * У каждой болезни — уникальное фото.
 */
export const DISEASE_TITLE_TO_IMAGE_FILENAME: Record<string, string> = {
  // Листья (diag_cat_leaves)
  'Мучнистая роса': 'Powdery mildew',
  'Антракноз': 'anthracnose',
  'Септориоз': 'septoria',
  'Ржавчина': 'rust',
  'Хлороз': 'chlorosis',
  'Краевой некроз': 'Marginal necrosis',
  'Бактериальная пятнистость': 'bacterial-leaf-spot',
  'Ложная мучнистая роса': 'downy-mildew',
  'Мозаичный вирус': 'Mosaic virus',
  'Солнечный ожог': 'Sunburn',
  // Стебель (diag_cat_stem)
  'Стеблевая гниль': 'black-root-rot',
  'Черная ножка': 'damping-off',
  'Бактериальный рак': 'crown-gall',
  'Фузариозное увядание': 'Fusarium wilt',
  'Вертициллез': 'verticillium',
  'Фитофтороз стебля': 'phytophthora',
  'Механический разрыв коры': 'Mechanical bark injury',
  'Этиоляция': 'etiolation',
  'Камедетечение': 'gummosis',
  'Стеблевая нематода': 'Stem nematode',
  // Корни (diag_cat_roots)
  'Корневая гниль': 'Root rot',
  'Залив корней': 'Root waterlogging',
  'Солевой ожог': 'Fertilizer salt burn',
  'Галловая нематода': 'root-knot-nematodes',
  'Закисание почвы': 'Soil acidification',
  'Трахеомикоз': 'Tracheomycosis',
  'Переохлаждение корней': 'Root chilling',
  'Питиоз': 'pythium',
  'Ризоктониоз': 'rhizoctonia',
  'Корневой червец': 'Root mealybug',
  // Вредители (diag_cat_pests)
  'Паутинный клещ': 'spider-mite',
  'Трипсы': 'thrips',
  'Мучнистый червец': 'mealybug',
  'Щитовка': 'scale',
  'Тля': 'aphid',
  'Белокрылка': 'whitefly',
  'Сциариды': 'fungus-gnat',
  'Минирующая моль': 'leafminer',
  'Цикадки': 'leafhopper',
  'Улитки и слизни': 'snail',
  // Цветы (diag_cat_flowers)
  'Серая гниль бутонов': 'Gray mold',
  'Опадание бутонов': 'Blossom drop',
  'Трипс цветочный': 'flower-thrips',
  'Деформация лепестков': 'Petal deformity',
  'Вирусное пестрение': 'Viral variegation',
  'Мумификация завязей': 'Ovary mummification',
  'Ботритис': 'botrytis',
  'Нехватка бора': 'Boron deficiency',
  'Ожог пыльцы': 'Pollen burn',
  'Короткое цветение': 'Short flowering',
  // Плоды (diag_cat_fruits)
  'Вершинная гниль': 'Blossom-end rot',
  'Горькая ямчатость': 'Bitter pit',
  'Парша': 'Apple scab',
  'Плодовая гниль': 'Fruit soft rot',
  'Растрескивание плодов': 'Fruit cracking',
  'Фитофтороз плодов': 'Late blight',
  'Черная плесень': 'sooty-mold',
  'Недоразвитость семян': 'Seed underdevelopment',
  'Медянка': 'bacterial-wilt',
  'Мумификация': 'Fruit mummification',
  // Общее (diag_cat_all)
  'Общее увядание': 'General wilt',
  'Азотное голодание': 'Nitrogen deficiency',
  'Тепловой шок': 'Heat shock',
  'Химическое отравление': 'Chemical poisoning',
  'Световое голодание': 'Light starvation',
  'Передозировка удобрений': 'Fertilizer overdose',
  'Засыхание точки роста': 'Growing point dieback',
  'Стагнация развития': 'sclerotinia',
  'Критический дефицит влаги': 'Critical water deficit',
  'Кислотный стресс почвы': 'Soil acid stress',
};
